version: "2"

networks:
  webappnetwork:
    driver: bridge

services:
  client_react:
    image: react-client
    build: ./client/react-client
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./client/react-client:/client
      - /client/react-client/node_modules
    links:
      - api
    networks:
      - webappnetwork

  client_angular:
    image: angular-client
    build: ./client/angular-client
    restart: always
    ports:
      - "4200:4200"
    volumes:
      - ./client/angular-client:/client2
      - /client/angular-client/node_modules
    links:
      - api
    networks:
      - webappnetwork

  api:
    image: webapp-api
    build: ./api
    restart: always
    ports:
      - "3080:3080"
    volumes:
      - ./api:/api
      - /api/node_modules
    depends_on:
      - mongodb
    networks:
      - webappnetwork

  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    volumes:
    - ./data-node:/data/db
    ports:
    - 27017:27017
    command: mongod --noauth --smallfiles
    networks:
    - webappnetwork


